<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-KSS2SG1G" failures="2" tests="2" name="Default test(failed)" time="0.145" errors="0" timestamp="2023-05-15T17:09:55 EDT">
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestFive" time="0.046">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at atech.ny.hooks.FailedTestCases.getTestFive(FailedTestCases.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestFive -->
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestTwo" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at atech.ny.hooks.FailedTestCases.getTestTwo(FailedTestCases.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestTwo -->
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestThree" time="0.0">
    <ignored/>
  </testcase> <!-- getTestThree -->
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestFour" time="0.0">
    <ignored/>
  </testcase> <!-- getTestFour -->
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestOne" time="0.0">
    <ignored/>
  </testcase> <!-- getTestOne -->
</testsuite> <!-- Default test(failed) -->
