<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-KSS2SG1G" failures="2" tests="5" name="Test" time="0.186" errors="0" timestamp="2023-05-15T16:55:10 EDT">
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestFive" time="0.044">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at atech.ny.hooks.FailedTestCases.getTestFive(FailedTestCases.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestFive -->
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestFour" time="0.002"/>
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestOne" time="0.002"/>
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestThree" time="0.003"/>
  <testcase classname="atech.ny.hooks.FailedTestCases" name="getTestTwo" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at atech.ny.hooks.FailedTestCases.getTestTwo(FailedTestCases.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestTwo -->
</testsuite> <!-- Test -->
